# Generated by Django 2.2.6 on 2019-10-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='text',
            field=models.CharField(max_length=280),
        ),
    ]
